version: "3"

services:
  master:
    image: "alkivi/salt:latest"
    privileged: true
    hostname: master
    container_name: master
    environment:
      SALT_USE: master
      LOG_LEVEL: info
      SALT_API: "yes"
    expose:
      - "4505"
      - "4506"
      - "8080"
    healthcheck:
      test: ["CMD", "telnet", "localhost", "4506"]
      interval: 5s
      timeout: 30s
      retries: 6

  minion:
    image: "alkivi/salt:latest"
    privileged: true
    hostname: minion
    container_name: minion
    depends_on:
      - master
    links:
      - master
    environment:
      SALT_USE: minion
      SALT_NAME: minion
      SALT_GRAINS: "{'test': 'minion'}"
      LOG_LEVEL: info
